### PR TITLE
Release/7.1.0

### PR DESCRIPTION
**Pull request by dairbuirabass**
## Checklist:
- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] I have assigned the correct milestone or created one if non-existent.
- [x] I have correctly labeled this pull request.
- [x] I have linked the corresponding issue in this description.
- [x] I have updated the corresponding Jira ticket.
- [x] I have requested a review from at least 2 reviewers
- [x] I have checked the base branch of this pull request
- [x] I have checked my code for any possible security vulnerabilities

### CODE REVIEW

**Review by supercid — CHANGES_REQUESTED** [review]
We need to wait for the indexer changes to be release. As of right now you're releasing 6.2.0 on top of 7.0

**Comment by dairbuirabass** [comment]
Ok @supercid I'll leave this one hanging at `7.1.0` then

**Comment by dairbuirabass** [comment]
@supercid this one's ready to be merged.

**Review by supercid — APPROVED** [review]
go for it

**Pull request merged**
