### PR TITLE
Support hide ouf of stock products config

### PR DESCRIPTION
**Pull request by unicoder88**
Hi guys,

Please review implementation of "Hide out of stock" setting.

Thanks :)

### CODE REVIEW

**Comment by chenliangde** [comment]
Hi,

Thanks for your contribution.  I am wondering what is the reason behind this PR? Is it for improving the performance?
Out of stock product would not be recommended even though the the plugin sends it to nosto backend. 

Thanks and Regards
Chen

**Comment by unicoder88** [comment]
They won't? Hmm, that's new. Let me test a little more and get back to you.
Thanks

**Comment by mridang** [comment]
@unicoder88 We'll close this for now. If this really is valid, and we've overlooked something, then please leave a comment and we'll reopen it. In Nosto, only products with the availability `InStock` is recommended, any other availability status will lead to the product not being recommended.

**Comment by unicoder88** [comment]
Thank you *thumbs up*

**Pull request closed without merging**
